-- Do not edit! This file was generated by blocks/protocol/adsbframer_spec.py

local radio = require('radio')
local jigs = require('tests.jigs')

jigs.TestBlock(radio.ADSBFramerBlock, {
    {
        desc = "Aircraft identification",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{callsign = "KLM1023", category = 0, df = 17, hex = "8d4840d6202cc371c32ce0576098", icao = 4735190, type_code = 4}}})}
    },
    {
        desc = "Airborne position, single even report",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{altitude = 38000, cpr_format = 0, cpr_lat = 93000, cpr_lon = 51372, df = 17, hex = "8d40621d58c382d690c8ac2863a7", icao = 4219421, surveillance_status = 0, type_code = 11}}})}
    },
    {
        desc = "Airborne position, even and odd report pair",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{altitude = 38000, cpr_format = 0, cpr_lat = 93000, cpr_lon = 51372, df = 17, hex = "8d40621d58c382d690c8ac2863a7", icao = 4219421, surveillance_status = 0, type_code = 11}}, {{altitude = 38000, cpr_format = 1, cpr_lat = 74158, cpr_lon = 50194, df = 17, hex = "8d40621d58c386435cc412692ad6", icao = 4219421, latitude = 52.26578017412606, longitude = 3.938912527901786, surveillance_status = 0, type_code = 11}}})}
    },
    {
        desc = "Surface position, even and odd report pair",
        args = {{reference = {lat = 51.99, lon = 4.375}}},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{cpr_format = 0, cpr_lat = 115609, cpr_lon = 116941, df = 17, groundspeed = 18.0, hex = "8c4841753aab238733c8cd4020b1", icao = 4735349, latitude = 52.32304000854492, longitude = 4.730472564697266, track = 140.625, type_code = 7}}, {{cpr_format = 1, cpr_lat = 39199, cpr_lon = 110269, df = 17, groundspeed = 16.0, hex = "8c4841753a8a35323faebdac702d", icao = 4735349, latitude = 52.320607072215964, longitude = 4.734734671456465, track = 98.4375, type_code = 7}}})}
    },
    {
        desc = "Airborne velocity",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{df = 17, gnss_baro_diff = 550, groundspeed = 159.20113064925135, hex = "8d485020994409940838175b284f", icao = 4739104, subtype = 1, track = 182.8803775528476, type_code = 19, vertical_rate = -832, vertical_rate_source = "gnss"}}})}
    },
    {
        desc = "Airborne position, Q=0 (Gillham) altitude",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{altitude = 50000, cpr_format = 0, cpr_lat = 93000, cpr_lon = 51372, df = 17, hex = "8d484175583232d690c8ac4ce22a", icao = 4735349, surveillance_status = 0, type_code = 11}}})}
    },
    {
        desc = "All-call reply",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({{{df = 11, hex = "5dabcdef8a6ab3", icao = 11259375}}})}
    },
    {
        desc = "Frame with a bit error",
        args = {},
        inputs = {radio.types.Bit.vector_from_array({1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0})},
        outputs = {require('radio.blocks.protocol.adsbframer').ADSBFrameType.vector_from_array({})}
    },
}, {epsilon = 1.0e-06})
